services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # HTTP management UI
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
